### ISSUE TITLE
is_sf fails if sf-onject is also a tibble

### ISSUE THREAD

**Issue by sjewo** [artod83/netmap#2]
Hi Matteo,

I ran into a small bug with your package. If the sf-object has additional class attributes the check in `is_sf()`  will fail  
https://github.com/artod83/netmap/blob/0ea239c6e7a0792f90d5ee9940927594f3bace12/R/link_network_map.R#L165 

In my example the class of my map was:
```
> class(map)
[1] "sf"         "tbl_df"     "tbl"        "data.frame" 
```

Maybe it is sufficient to check for `sf` and `data.frame` ?

```
is_sf <- function(m){
  clsf=class(m)
  if(!all(c("sf", "data.frame") %in% clsf)) {
    message(paste0("Invalid sf object supplied"))
    return(FALSE)
  } else {
    return(TRUE)
  }
}
```

Best,
Sebastian

**Comment by artod83** [comment]
Hello Sebastian, thanks for noticing this issue. I have uploaded version 0.1.4 to CRAN with your fix.
